layout_spectrum: 1
typography_spectrum: 0.4234042
color:
  saturation: 0.8726411
  lightness: 0.8786183
  brandStrength: 1
  brandColors:
    - '#FFFFFF'
    - '#70A8A9'
    - '#4B4F50'
    - '#BEBEBF'
    - '#6D6D6D'
  rhythmicContrast: 0.912513
name: LUX Technologies
